// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZSAXqk7UFthj7358IYOHqWjHwUX5_yI',
    appId: '1:149691930473:web:19023561709a58f72bcff8',
    messagingSenderId: '149691930473',
    projectId: 'student-project-group',
    authDomain: 'student-project-group.firebaseapp.com',
    storageBucket: 'student-project-group.firebasestorage.app',
    measurementId: 'G-F31TZP3SRN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcD2xzlERuLl7Sy4Zmcxtdv486hMVI6os',
    appId: '1:149691930473:ios:d6e9f7c168c5b3f72bcff8',
    messagingSenderId: '149691930473',
    projectId: 'student-project-group',
    storageBucket: 'student-project-group.firebasestorage.app',
    iosBundleId: 'com.example.studentMarksManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcD2xzlERuLl7Sy4Zmcxtdv486hMVI6os',
    appId: '1:149691930473:ios:d6e9f7c168c5b3f72bcff8',
    messagingSenderId: '149691930473',
    projectId: 'student-project-group',
    storageBucket: 'student-project-group.firebasestorage.app',
    iosBundleId: 'com.example.studentMarksManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZSAXqk7UFthj7358IYOHqWjHwUX5_yI',
    appId: '1:149691930473:web:48a80e0279a6a25c2bcff8',
    messagingSenderId: '149691930473',
    projectId: 'student-project-group',
    authDomain: 'student-project-group.firebaseapp.com',
    storageBucket: 'student-project-group.firebasestorage.app',
    measurementId: 'G-BZBY4QQJC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaF6q3GFWq1PRn0uDutw716UvuroLFys4',
    appId: '1:149691930473:android:aa3a577fb820897c2bcff8',
    messagingSenderId: '149691930473',
    projectId: 'student-project-group',
    storageBucket: 'student-project-group.firebasestorage.app',
  );

}